from .block import *
from .funcDec import *
from .funcCall import *
from .identifier import *
from .println import *
from .readln import *
from .s_if import *
from .s_return import *
from .s_while import *
from .variable import *
